branch-defaults:
  deploy:
    artifact: ./www/Archive.zip
  dev:
    environment: udagram-mscharf-dev-dev
global:
  application_name: udagram-mscharf-dev
  branch: null
  default_ec2_keyname: ms-udacity
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
